// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LinkDescription link description
//
// swagger:model LinkDescription
type LinkDescription struct {

	// href
	Href string `json:"href,omitempty"`

	// media type
	MediaType string `json:"mediaType,omitempty"`

	// rel
	Rel string `json:"rel,omitempty"`
}

// Validate validates this link description
func (m *LinkDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this link description based on context it is used
func (m *LinkDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LinkDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinkDescription) UnmarshalBinary(b []byte) error {
	var res LinkDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
