// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PropertyPutBody property put body
//
// swagger:model PropertyPutBody
type PropertyPutBody map[string]string

// Validate validates this property put body
func (m PropertyPutBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this property put body based on context it is used
func (m PropertyPutBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
